OSOE-93: Fixes
Lombiq/Orchard-Chart.js pull request #23
Opened 2022-05-17 21:37 UTC by dministro

OSOE-93

2022-05-24 17:41 UTC, DAud-IcI requested changes
Keep the copyright dates as 2021 [because that's the date of the initial commit](https://github.com/Lombiq/Orchard-Chart.js/commit/b77c3d7f7bbb46aa4f09d180005457d5e46a0aa7).

2022-05-25 13:51 UTC, DAud-IcI requested changes

2022-05-25 13:51 UTC, DAud-IcI commented on License.md
> +Copyright © 2022, [Lombiq Technologies Ltd.](https://lombiq.com)
You forgot this one

2022-05-26 16:56 UTC, dministro commented
@Piedone I made nuget related changes here

2022-05-29 20:13 UTC, DAud-IcI approved these changes

2022-05-30 14:04 UTC, merged